# Generated by Django 2.2.6 on 2019-10-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lip',
            name='brand',
            field=models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.CASCADE, to='cosmos.Brand'),
        ),
        migrations.AlterField(
            model_name='lip',
            name='thumbnail',
            field=models.CharField(max_length=100),
        ),
    ]
