# Generated by Django 2.2.6 on 2019-10-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0002_auto_20191030_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lip',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmos.Brand'),
        ),
        migrations.AlterField(
            model_name='lip',
            name='thumbnail',
            field=models.CharField(max_length=150),
        ),
    ]
