# Generated by Django 2.2.6 on 2019-11-02 09:44

import cosmos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0004_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lip',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmos.Brand', verbose_name=cosmos.models.Brand),
        ),
    ]
