# Generated by Django 2.2.6 on 2019-11-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0005_auto_20191102_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lip',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmos.Brand'),
        ),
    ]
