# Generated by Django 2.2.7 on 2019-11-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_ml_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='result',
            field=models.CharField(default='NONE', max_length=30),
        ),
    ]
