# Generated by Django 2.2.7 on 2019-11-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_auto_20191123_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
