# Generated by Django 2.2.7 on 2019-11-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20191123_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ml',
            old_name='file',
            new_name='image',
        ),
    ]
