# Generated by Django 2.2.6 on 2019-11-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0010_auto_20191126_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='result',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ml',
            name='user_id',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
