# Generated by Django 2.2.6 on 2019-11-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0014_auto_20191126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='base',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.BaseOption'),
        ),
        migrations.AlterField(
            model_name='ml',
            name='result',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='ml',
            name='user_id',
            field=models.CharField(default='NONE', max_length=30),
        ),
    ]
