# Generated by Django 2.2.6 on 2019-11-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20191116_1921'),
        ('ml', '0017_auto_20191126_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Base'),
        ),
    ]
