# Generated by Django 2.2.6 on 2019-12-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0018_ml_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml',
            name='output_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
