# Generated by Django 2.2.6 on 2019-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheek',
            name='category',
            field=models.CharField(choices=[('CHK_B', 'Blusher'), ('CHK_C', 'Contouring'), ('CHK_H', 'Highlighter')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cheekoption',
            name='color',
            field=models.CharField(choices=[('CHK_RD', 'Red'), ('CHK_PK', 'Pink'), ('CHK_OR', 'Orange')], max_length=6),
        ),
    ]
