# Generated by Django 2.2.6 on 2019-11-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0003_brand_name_ko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('P', 'Powder'), ('CU', 'Cushion'), ('C', 'Concealer'), ('F', 'Foundation'), ('PR', 'Primer'), ('B', 'BB & CC')], max_length=1)),
                ('img_url', models.TextField(default='//:0')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='BaseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('LT', 'under 21'), ('MD', '21 ~ 23'), ('DK', 'over 23')], max_length=2)),
                ('sub_color', models.CharField(default=None, max_length=30, null=True)),
                ('color_hex', models.CharField(max_length=10)),
                ('optionName', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Base')),
            ],
        ),
    ]
