# Generated by Django 2.2.6 on 2019-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseoption',
            name='color',
            field=models.CharField(choices=[('LT', 'under 21'), ('MD', '21 ~ 23'), ('DK', 'over 23'), ('NO', 'Other type')], max_length=2),
        ),
    ]
