# Generated by Django 2.2.6 on 2019-11-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0003_brand_name_ko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eyebrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('img_url', models.TextField(default='//:0')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eyeliner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('img_url', models.TextField(default='//:0')),
                ('form', models.CharField(choices=[('L', 'Liquid'), ('P', 'Pencil'), ('G', 'Gel')], default=None, max_length=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mascara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('img_url', models.TextField(default='//:0')),
                ('func', models.CharField(choices=[('L', 'Long Lash'), ('C', 'Curling'), ('V', 'Volume')], max_length=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MascaraOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BK', 'Black'), ('DB', 'Deep Brown'), ('LB', 'Light Brown'), ('EX', 'Etc')], max_length=2)),
                ('color_hex', models.CharField(max_length=10)),
                ('optionName', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Mascara')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eyeshadow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('img_url', models.TextField(default='//:0')),
                ('if_pallette', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyelinerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BK', 'Black'), ('DB', 'Deep Brown'), ('LB', 'Light Brown'), ('EX', 'Etc')], max_length=2)),
                ('color_hex', models.CharField(max_length=10)),
                ('optionName', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Eyeliner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyebrowOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BK', 'Black'), ('DB', 'Deep Brown'), ('LB', 'Light Brown'), ('EX', 'Etc')], max_length=2)),
                ('color_hex', models.CharField(max_length=10)),
                ('optionName', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Eyebrow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
