# Generated by Django 2.2.6 on 2019-11-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('lip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lip',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lip',
            name='category',
            field=models.CharField(choices=[('S', 'Stick'), ('G', 'Gloss'), ('B', 'Balm'), ('T', 'Tint')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
