# Generated by Django 2.2.6 on 2019-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0003_lipoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipoption',
            name='optionName',
            field=models.CharField(default='tmpoption', max_length=30),
            preserve_default=False,
        ),
    ]
