# Generated by Django 2.2.6 on 2019-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0004_lipoption_optionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lip',
            name='img_url',
            field=models.TextField(default='//:0'),
        ),
    ]
