# Generated by Django 2.2.6 on 2019-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0005_lip_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipoption',
            name='color_hex',
            field=models.CharField(default='#ffffff', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lipoption',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('CR', 'Coral'), ('PK', 'Pink'), ('OR', 'Orange')], default='RD', max_length=2),
        ),
    ]
