# Generated by Django 2.2.6 on 2019-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0007_auto_20191111_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipoption',
            name='sub_color',
            field=models.CharField(default=None, max_length=30,null=True),
        ),
    ]
