# Generated by Django 2.2.6 on 2019-11-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0008_lipoption_sub_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='lip.Lip'),
        ),
    ]
