# Generated by Django 2.2.6 on 2019-11-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0009_auto_20191117_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipoption',
            name='sub_color',
            field=models.CharField(default='#ffffff', max_length=30),
            preserve_default=False,
        ),
    ]
