# Generated by Django 2.2.6 on 2019-11-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0011_auto_20191126_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='lip',
            name='product_url',
            field=models.CharField(default='//:0', max_length=255),
        ),
        migrations.AlterField(
            model_name='lip',
            name='img_url',
            field=models.CharField(default='//:0', max_length=255),
        ),
    ]
