# Generated by Django 2.2.6 on 2019-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip', '0012_auto_20191126_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lip',
            name='category',
            field=models.CharField(choices=[('LIP_S', 'Stick'), ('LIP_G', 'Gloss'), ('LIP_B', 'Balm'), ('LIP_T', 'Tint')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lip',
            name='form',
            field=models.CharField(choices=[('LIP_M', 'Matte'), ('LIP_G', 'Glossy'), ('LIP_N', 'None')], default='LIP_N', max_length=5),
        ),
        migrations.AlterField(
            model_name='lipoption',
            name='color',
            field=models.CharField(choices=[('LIP_RD', 'Red'), ('LIP_PK', 'Pink'), ('LIP_OR', 'Orange'), ('LIP_PU', 'Purple')], max_length=6),
        ),
    ]
