# Generated by Django 2.2.6 on 2019-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.TextField(default='//:0'),
        ),
    ]
